from rest_framework import serializers
from .models import CaseDetails

class CaseDetailSerializer(serializers.ModelSerializer):
    class Meta:
        model = CaseDetails
        fields = (
            'status',
            'reporter_name',
            'phone_number',
            'case_per_page',
            'alt_phone_number',
            'reported_date',
            'reported_time',
            'location',
            'landmark',
            'pincode',
            'can_drop_animal',
            'animal_marking',
            'animal_color',
            'animal_picture_1',
            'animal_picture_2',
            'animal_picture_3',
            'animal_picture_4',
            'animal_picture_5',
            'reporter_photo_id_1',
            'reporter_photo_id_2',
            'consent_form',
            'animal_type',
            'age_of_animal',
            'pickup_date',
            'pickup_time',
            'animal_temperament',
            'gender',
            'pregnant',
            'breed',
            'catchable',
            'medical_history_other_issues',
            'fit_for_surgery',
            'vaccinated',
            'dewormed',
            'other_details',
            'blood_test_report_1',
            'blood_test_report_2',
            'blood_test_report_3',
            'blood_test_report_4',
            'blood_test_report_5',
            'admission_date',
            'vet_assigned',
            'operation_date',
            'operation_cost',
            'operation_start_time',
            'operation_end_time',
            'operation_outcome',
            'cause_of_failure',
            'after_operation_pic_1',
            'after_operation_pic_2',
            'after_operation_pic_3',
            'after_operation_pic_4',
            'after_operation_pic_5',
            'post_op_comments',
            'cage_num',
            'post_op_start_date',
            'post_op_start_time',
            'release_date',
            'release_time',
            'other_comments',
            'medicine_photos_1',
            'medicine_photos_2',
            'medicine_photos_3',
            'medicine_photos_4',
            'medicine_photos_5',
        )
