# Generated by Django 3.2.13 on 2022-06-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('reported_time', models.TimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('landmark', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=100, null=True)),
                ('can_drop_animal', models.CharField(blank=True, max_length=3, null=True)),
                ('animal_marking', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_color', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_picture_1', models.FileField(default='images/upload_pic.jpg', upload_to='images/')),
                ('animal_picture_2', models.FileField(default='images/upload_pic.jpg', upload_to='images/')),
                ('animal_picture_3', models.FileField(default='images/upload_pic.jpg', upload_to='images/')),
                ('animal_picture_4', models.FileField(default='images/upload_pic.jpg', upload_to='images/')),
                ('animal_picture_5', models.FileField(default='images/upload_pic.jpg', upload_to='images/')),
                ('reporter_photo_id_1', models.FileField(default='images/upload_pic.jpg', upload_to='images/')),
                ('reporter_photo_id_2', models.FileField(default='images/upload_pic.jpg', upload_to='images/')),
                ('animal_type', models.CharField(blank=True, max_length=100, null=True)),
                ('age_of_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('animal_temperament', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('pregnant', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('catchable', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_history_other_issues', models.TextField(blank=True, null=True)),
                ('fit_for_surgery', models.CharField(blank=True, max_length=100, null=True)),
                ('vaccinated', models.CharField(blank=True, max_length=100, null=True)),
                ('dewormed', models.CharField(blank=True, max_length=100, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('blood_test_report_1', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('blood_test_report_2', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('blood_test_report_3', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('blood_test_report_4', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('blood_test_report_5', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('vet_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('operation_cost', models.FloatField(blank=True, null=True)),
                ('operation_start_time', models.TimeField(blank=True, null=True)),
                ('operation_end_time', models.TimeField(blank=True, null=True)),
                ('operation_outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('cause_of_failure', models.TextField(blank=True, null=True)),
                ('after_operation_pic_1', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('after_operation_pic_2', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('after_operation_pic_3', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('after_operation_pic_4', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('after_operation_pic_5', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('post_op_comments', models.TextField(blank=True, null=True)),
                ('cage_num', models.CharField(blank=True, max_length=100, null=True)),
                ('post_op_start_date', models.DateField(blank=True, null=True)),
                ('post_op_start_time', models.TimeField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_time', models.TimeField(blank=True, null=True)),
                ('other_comments', models.TextField(blank=True, null=True)),
                ('medicine_photos_1', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('medicine_photos_2', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('medicine_photos_3', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('medicine_photos_4', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
                ('medicine_photos_5', models.FileField(blank=True, default='images/upload_pic.jpg', null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Case Details',
            },
        ),
    ]
