# Generated by Django 4.0.5 on 2022-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sterilization_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='case_per_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
