# Generated by Django 4.0.5 on 2022-07-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sterilization_module', '0002_casedetails_case_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetails',
            name='consent_form',
            field=models.FileField(default='images/upload_pic.jpg', upload_to='images/'),
        ),
    ]
